### ISSUE TITLE
'LaunchError Events: [] Error Type: PermissionDenied' and 's3transfer.exceptions import RetriesExceededError' Error Messages

### ISSUE THREAD

**Issue by jhonangelmireles** [aws-samples/aws-lambda-extensions#38]
I just want to share and couple of  issues I faced today while deploying the template under 'https://github.com/aws-samples/aws-lambda-extensions/tree/main/s3-logs-extension-demo-zip-archive'

**Error 1:**

`START RequestId: d3594b49-d2bd-49b2-9cca-4cc7beafe05b Version: $LATEST
EXTENSION	Name: logs_api_http_extension.py	State: LaunchError	Events: []	Error Type: PermissionDenied
END RequestId: d3594b49-d2bd-49b2-9cca-4cc7beafe05b
REPORT RequestId: d3594b49-d2bd-49b2-9cca-4cc7beafe05b	Duration: 1.49 ms	Billed Duration: 2 ms	Memory Size: 128 MB	Max Memory Used: 6 MB	
XRAY TraceId: 1-60425254-30ebc4cf7841f6fc52addcb3	SegmentId: 121c26332f517724	Sampled: true	
RequestId: d3594b49-d2bd-49b2-9cca-4cc7beafe05b Error: fork/exec /opt/extensions/logs_api_http_extension.py: permission denied
Extension.LaunchError`

**Reason Error 1:**
The reason behind the issue is that the underlying Lambda container requires permissions to execute the 'extensions/logs_api_http_extension.py' file.

**Solution Error 1:**
Run the below comand to add execution permissions to the python script:
`$ chmod +x logs_api_http_extension.py`

**Error 2:**

`extension.extensions_api_client: Registering Extension at ExtensionsAPI address: http://127.0.0.1:9001/2020-01-01/extension
extension.logs_api_client: Subscribing to Logs API on http://127.0.0.1:9001/2020-08-15/logs
extension.http_listener: Running HTTP Server on 0.0.0.0:4243
LOGS	Name: logs_api_http_extension.py	State: Subscribed	Types: [platform,function]
Traceback (most recent call last):
  File "/opt/extensions/logs_api_http_extension.py", line 134, in <module>
    main()
  File "/opt/extensions/logs_api_http_extension.py", line 131, in main
    ext.run_forever()
  File "/opt/extensions/logs_api_http_extension.py", line 67, in run_forever
    s3 = boto3.resource('s3')
  File "/opt/extensions/lib/boto3/__init__.py", line 102, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/opt/extensions/lib/boto3/session.py", line 384, in resource
    client = self.client(
  File "/opt/extensions/lib/boto3/session.py", line 258, in client
    return self._session.create_client(
  File "/opt/extensions/lib/botocore/session.py", line 834, in create_client
    client = client_creator.create_client(
  File "/opt/extensions/lib/botocore/client.py", line 81, in create_client
    cls = self._create_client_class(service_name, service_model)
  File "/opt/extensions/lib/botocore/client.py", line 111, in _create_client_class
    self._event_emitter.emit(
  File "/opt/extensions/lib/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/opt/extensions/lib/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/opt/extensions/lib/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/opt/extensions/lib/boto3/utils.py", line 61, in _handler
    module = import_module(module)
  File "/opt/extensions/lib/boto3/utils.py", line 52, in import_module
    __import__(name)
  File "/opt/extensions/lib/boto3/s3/inject.py", line 15, in <module>
    from boto3.s3.transfer import create_transfer_manager
  File "/opt/extensions/lib/boto3/s3/transfer.py", line 127, in <module>
    from s3transfer.exceptions import RetriesExceededError as \
  File "/opt/extensions/lib/s3transfer/__init__.py", line 134, in <module>
    import concurrent.futures
  File "/opt/extensions/lib/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/opt/extensions/lib/concurrent/futures/_base.py", line 414
    raise exception_type, self._exception, self._traceback
^
SyntaxError: invalid syntax
`
**Reason Error 1:**
This is an issue generated in the build step, when python installs the boto3 dependencies.

See below link for more details:
https://github.com/boto/boto3/issues/1399#issuecomment-522342709

**Solution Error 2:**
The straight forward solution in my case was to build the SAM application using docker containers. 
`$ sam build --use-container
 $ sam deploy`

**Comment by santiagocardenas** [comment]
Thank you for reporting these @jhonangelmireles!

@julianwood can you please ensure to include these in the readme?

**Comment by julianwood** [comment]
Thanks, I've updated the README with the suggestions.
